const actionsTypes = {
    TEST_MESSAGE: "TEST_MESSAGE",

    // user
    USER_AUTHENTICATE: 'USER_AUTHENTICATE',
    LOGIN_CHECK: 'LOGIN_CHECK',

    // menu
    STORE_INIT: 'STORE_INIT',
    GET_MENUS: 'GET_MENUS',
    CREATE_MENU: 'CREATE_MENU',
    GET_MENU: 'GET_MENU',
    DELETE_MENU: 'DELETE_MENU',
    UPDATE_MENU: 'UPDATE_MENU',
    DELETE_MENU_IMAGE: 'DELETE_MENU_IMAGE',
}

export default actionsTypes;